# Generated by Django 5.0 on 2023-12-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="comments",
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="contact",
            name="desc",
            field=models.TextField(),
        ),
    ]
