# Generated by Django 5.0 on 2023-12-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_contact_comments_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="mobilenumber",
            field=models.IntegerField(),
        ),
    ]
